"""Clipboard image paste — Ctrl-V interception with host-side clipboard read.

Both agents bind ``Ctrl-V`` (the raw ``\\x16`` byte) as the
keystroke that pastes a clipboard image into their interactive composer.
On the host that triggers a macOS / Linux clipboard API call which can't
reach the host pasteboard from inside a Docker sandbox — so without help
the keystroke produces "no image found in clipboard."

This module is the host-side bypass.  The PTY proxy sits between the
user's terminal and the container's TTY; we scan its stdin stream for
``\\x16``, and on each occurrence we ask the host OS for the current
clipboard image.  If a PNG comes back we save it to a per-task bind-
mounted directory and swap the keystroke for the agent's preferred
file reference (set per-backend via
``AgentBackend.format_image_reference``).  If the clipboard is empty
or text, the byte passes through unchanged so it retains its normal
terminal meaning (vim visual-block, bash literal-insert, etc.).

The protocol layer here is independent of the file-descriptor plumbing
in ``pty_proxy``; we operate on byte streams only so the whole thing is
unit-testable without a real PTY.
"""

import logging
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Callable

import seekr_hatchery.ui as ui

logger = logging.getLogger("hatchery")


# ── Magic-byte sniff ──────────────────────────────────────────────────────────

_MAGIC: tuple[tuple[bytes, str], ...] = (
    (b"\x89PNG\r\n\x1a\n", "png"),
    (b"\xff\xd8\xff", "jpg"),
    (b"GIF87a", "gif"),
    (b"GIF89a", "gif"),
)


def sniff_extension(data: bytes) -> str:
    """Return file extension for *data* based on a leading magic-byte sniff."""
    for magic, ext in _MAGIC:
        if data.startswith(magic):
            return ext
    # WebP has a split signature: "RIFF....WEBP" with size in between.
    if len(data) >= 12 and data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "webp"
    return "bin"


# ── Host clipboard read ──────────────────────────────────────────────────────

# Wall-clock budget for the host clipboard probe.  The osascript / xclip
# spawn itself is the dominant cost (~50–150 ms on Mac); 2 s is plenty.
_HOST_CLIPBOARD_TIMEOUT_S: float = 2.0


def _read_host_clipboard_image() -> bytes | None:
    """Return host clipboard contents as image bytes, or ``None``.

    Returns ``None`` whenever the clipboard does not currently hold an
    image, the platform's tool is missing/unsupported, or the spawn
    times out.  Never raises — failures degrade to ``None`` so the
    Ctrl-V keystroke can fall through to the agent unchanged.
    """
    if sys.platform == "darwin":
        return _read_clipboard_darwin()
    if sys.platform.startswith("linux"):
        return _read_clipboard_linux()
    return None


def _read_clipboard_darwin() -> bytes | None:
    """Extract PNG image from macOS pasteboard via ``osascript``."""
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        target = Path(tmp.name)
    # ``target`` is generated by tempfile.NamedTemporaryFile; its random
    # component is drawn from [a-zA-Z0-9_] so direct interpolation into
    # the AppleScript body is safe.  If this path ever takes a caller-
    # supplied component, switch to env-var indirection via
    # ``system attribute "HATCHERY_TMP"`` and pass it through subprocess
    # env to avoid script injection.
    script = (
        "try\n"
        "  set img to (the clipboard as «class PNGf»)\n"
        f'  set fhandle to open for access POSIX file "{target}" with write permission\n'
        "  write img to fhandle\n"
        "  close access fhandle\n"
        '  return "ok"\n'
        "on error\n"
        '  return "no"\n'
        "end try\n"
    )
    try:
        result = subprocess.run(
            ["osascript", "-e", script],
            capture_output=True,
            text=True,
            timeout=_HOST_CLIPBOARD_TIMEOUT_S,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as exc:
        logger.debug("host clipboard (darwin): %s", exc)
        target.unlink(missing_ok=True)
        return None
    if result.returncode == 0 and result.stdout.strip() == "ok":
        try:
            data = target.read_bytes()
        except OSError as exc:
            logger.debug("host clipboard (darwin): read failed: %s", exc)
            data = None
        target.unlink(missing_ok=True)
        return data if data else None
    target.unlink(missing_ok=True)
    return None


def _read_clipboard_linux() -> bytes | None:
    """Extract image bytes from the Linux clipboard via wl-paste / xclip."""
    for cmd in (
        ["wl-paste", "--type", "image/png"],
        ["xclip", "-selection", "clipboard", "-t", "image/png", "-o"],
    ):
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                timeout=_HOST_CLIPBOARD_TIMEOUT_S,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as exc:
            logger.debug("host clipboard (linux %s): %s", cmd[0], exc)
            continue
        if result.returncode == 0 and result.stdout:
            return result.stdout
    return None


# ── File save ────────────────────────────────────────────────────────────────


def save_image(data: bytes, target_dir: Path) -> Path:
    """Write *data* to a uniquely-named file under *target_dir*.

    File name carries an ISO-ish timestamp so a series of pastes sort
    chronologically and so the user can tell at a glance which is which.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    ext = sniff_extension(data)
    stamp = datetime.now().strftime("%Y%m%dT%H%M%S")
    # Disambiguate within the same second.
    counter = 0
    while True:
        suffix = f"-{counter}" if counter else ""
        path = target_dir / f"paste-{stamp}{suffix}.{ext}"
        if not path.exists():
            break
        counter += 1
    path.write_bytes(data)
    return path


# ── Paste interceptor ─────────────────────────────────────────────────────────


@dataclass
class PasteInputResult:
    """Bytes the PTY proxy should forward to the agent."""

    to_agent: bytes = b""


# Paste-keystroke triggers — sequences we treat as "user wants to paste an
# image."  When one of these appears in stdin and the host clipboard holds
# an image, we replace it with the agent's reference; otherwise it passes
# through unchanged so it keeps its normal terminal meaning.
#
# Two forms today:
#   * 0x16 — the standard Ctrl-V byte that most TUIs
#   * ESC[118;5u — Ctrl-V under the kitty keyboard protocol (CSI u).
#     Codex enables this protocol on startup; in that mode keys arrive
#     as escape sequences instead of raw bytes, so the 0x16 form never
#     appears for Codex even though it's the same physical keystroke.
_PASTE_TRIGGERS: tuple[bytes, ...] = (
    b"\x16",
    b"\x1b[118;5u",
)


class PasteInterceptor:
    """Stateless Ctrl-V interceptor for clipboard image paste.

    One instance per interactive session.  No state machine, no
    capture mode, no timeouts — every call to :meth:`feed_stdin` is
    independent.  The interceptor scans the chunk for any of the
    paste-keystroke triggers (see ``_PASTE_TRIGGERS``) and replaces
    each occurrence with the agent's formatted file reference when
    the host clipboard holds an image at that moment; otherwise the
    trigger passes through unchanged.
    """

    def __init__(
        self,
        target_dir: Path,
        format_image_reference: Callable[[Path], str],
    ) -> None:
        self._target_dir = target_dir
        self._format_image_reference = format_image_reference

    def feed_stdin(self, chunk: bytes) -> PasteInputResult:
        """Process *chunk* from the user's stdin.

        Hot path is the no-trigger branch: plain typing passes through
        without spawning any subprocess, so the per-keystroke overhead
        is at most one cheap membership test per trigger pattern.
        """
        if not any(trigger in chunk for trigger in _PASTE_TRIGGERS):
            return PasteInputResult(to_agent=chunk)
        return PasteInputResult(to_agent=self._intercept_paste_keystroke(chunk))

    # ── Internals ─────────────────────────────────────────────────────────────

    def _intercept_paste_keystroke(self, chunk: bytes) -> bytes:
        """Replace each paste trigger in *chunk* with the agent's reference
        when the host clipboard holds an image; pass it through otherwise.

        Triggers can be multi-byte (e.g. the kitty CSI-u form
        ``ESC[118;5u``), so we scan position-by-position and match each
        trigger atomically.
        """
        out = bytearray()
        i = 0
        while i < len(chunk):
            matched: bytes | None = None
            for trigger in _PASTE_TRIGGERS:
                if chunk[i : i + len(trigger)] == trigger:
                    matched = trigger
                    break
            if matched is None:
                out.append(chunk[i])
                i += 1
                continue
            image_bytes = _read_host_clipboard_image()
            if image_bytes is not None:
                out.extend(self._inject_image(image_bytes))
            else:
                # No image — preserve the original trigger so it keeps its
                # normal terminal meaning (vim visual-block, etc.).
                out.extend(matched)
            i += len(matched)
        return bytes(out)

    def _inject_image(self, data: bytes) -> bytes:
        """Save *data* to disk and return bytes to type into the agent."""
        try:
            path = save_image(data, self._target_dir)
        except OSError as exc:
            logger.warning("Failed to save pasted image: %s", exc)
            return b""
        ref = self._format_image_reference(path)
        ui.info(f"📎 Pasted image saved as {path.name}")
        return ref.encode("utf-8") + b" "
